import { ProjectDataType } from '@/app/utils/definitions/projectDataType';

export const projectData: Record<string, ProjectDataType> = {
    'QoreAudit and QoreMail app': {
        title: 'QoreAudit and QoreMail app',
        shortDescription: 'Web application',
        description:
            'Developed web applications for monitoring the status of a chain of processes performed by QoreAudit, with the web app designed to be a Progressive Web App (PWA). The applications aimed to provide users with real-time insights into the status and performance of the auditing processes, enhancing monitoring and decision-making capabilities.',
        logo: 'coginov-logo.webp',
        image: 'qoreaudit.webp',
        skills: [
            'Git',
            'Github',
            'HTML',
            'CSS',
            'Javascript',
            'Typescript',
            'React',
            'NodeJs',
            '.NET',
        ],
        company: 'Coginov',
        years: [2022, 2023, 2024],
        prevLink: '',
        nextLink: '/project/QoreUltima SharePoint app',
    },
    'QoreUltima SharePoint app': {
        title: 'QoreUltima SharePoint app',
        shortDescription: 'Sharepoint extension',
        description:
            'Developed a set of SharePoint extensions that enable the transfer of data stored in SharePoint to QoreUltima, a content processing application. The extensions facilitated seamless integration between SharePoint and QoreUltima, allowing for the efficient processing and management of content across both platforms.',
        logo: 'coginov-logo.webp',
        image: 'extension.webp',
        skills: [
            'Git',
            'Github',
            'HTML',
            'CSS',
            'Javascript',
            'Typescript',
            'React',
            'Sharepoint',
        ],
        company: 'Coginov',
        years: [2023, 2024],
        prevLink: '/project/QoreAudit and QoreMail app',
        nextLink: '/project/Signup flow',
    },
    'Signup flow': {
        title: 'Signup flow',
        shortDescription: 'Shopify module',
        description:
            'Implemented several rounds of A/B testing to optimize the signup flow for improved user acquisition and retention. Conducted tests on each step of the signup process to identify and implement changes that would reduce friction and increase conversion rates.',
        logo: 'shopify-logo.webp',
        image: 'sp-signup.webp',
        skills: [
            'Git',
            'Github',
            'HTML',
            'CSS',
            'Javascript',
            'Typescript',
            'React',
            'GraphQl',
            'NodeJs',
        ],
        company: 'Shopify',
        years: [2021, 2023],
        prevLink: '/project/QoreUltima SharePoint app',
        nextLink: '/project/Redesign of de plan and prices page',
    },
    'Redesign of de plan and prices page': {
        title: 'Redesign of de plan and prices page',
        shortDescription: 'Shopify page',
        description:
            "Developed the redesign and A/B testing of the 'Plan and Prices' page on the Shopify platform to enhance user experience and drive conversions. Implemented data-driven design changes based on user feedback and analytics to optimize the page for increased engagement and sales.",
        logo: 'shopify-logo.webp',
        image: 'sp-planprices..webp',
        skills: [
            'Git',
            'Github',
            'HTML',
            'CSS',
            'Javascript',
            'Typescript',
            'React',
            'GraphQl',
            'NodeJs',
        ],
        company: 'Shopify',
        years: [2020, 2021],
        prevLink: '/project/Signup flow',
        nextLink: '/project/Export-Import Shopify App',
    },
    'Export-Import Shopify App': {
        title: 'Export-Import Shopify App',
        shortDescription: 'Shopify app',
        description:
            'Transfer to the core module a Shopify app that enables users to easily import and export data from/to a list of supported platforms, facilitating seamless data migration and synchronization. The app provides a user-friendly interface and robust features for managing and transferring data.',
        logo: 'shopify-logo.webp',
        skills: [
            'Git',
            'Github',
            'HTML',
            'CSS',
            'Javascript',
            'Typescript',
            'React',
            'GraphQl',
            'NodeJs',
        ],
        company: 'Shopify',
        years: [2019, 2020],
        prevLink: '/project/Redesign of de plan and prices page',
        nextLink: '/project/Service enablement web app',
    },
    'Service enablement web app': {
        title: 'Service enablement web app',
        shortDescription: 'Web application',
        description:
            'Created a new web application for Service Enablement, aimed at monitoring and controlling bandwidth usage to allocate resources more efficiently. The application provides a comprehensive suite of tools for administrators to manage and optimize network performance.',
        logo: 'nokia-logo.webp',
        image: 'nokia.webp',
        skills: [
            'Git',
            'Github',
            'HTML',
            'CSS',
            'Javascript',
            'Typescript',
            'React',
            'Redux',
        ],
        company: 'Nokia',
        years: [2018, 2019],
        prevLink: '/project/Export-Import Shopify App',
        nextLink: '/project/ToolboxApp',
    },
    ToolboxApp: {
        title: 'ToolboxApp',
        shortDescription: 'Mobile app',
        description:
            'Created a mobile app for Club Assist that simplifies the search for a battery in the field and enables technicians to enter data regarding the battery search. The app streamlines the process of locating and servicing batteries, enhancing efficiency and accuracy for technicians.',
        logo: 'clubassist-logo.webp',
        skills: [
            'Git',
            'Github',
            'HTML',
            'CSS',
            'Javascript',
            'Typescript',
            'Ionic',
            'AngularJs',
        ],
        company: 'Club Assist',
        years: [2017, 2018],
        prevLink: '/project/Service enablement web app',
        nextLink: '/project/FitmentPortal',
    },
    FitmentPortal: {
        title: 'FitmentPortal',
        shortDescription: 'Application',
        description:
            'Maintenance tasks of the Fitment portal (Online Order, instant-quote widget)the FitmentPortal facilitated automotive information for battery replacements',
        logo: 'clubassist-logo.webp',
        skills: [
            'Git',
            'Github',
            'HTML',
            'CSS',
            'Javascript',
            'Typescript',
            'Angular2',
            'Redux',
        ],
        company: 'Club Assist',
        years: [2017, 2018],
        prevLink: '/project/ToolboxApp',
        nextLink: '/project/Online Check-in',
    },
    'Online Check-in': {
        title: 'Online Check-in',
        shortDescription: 'Module for Web app',
        description:
            'Develop a new Online check-in experience, with the purpose to attract more travelers to use it, the site was developed to support other branches: Online check-in for Celebrity Cruises, and Azamara Cruises.',
        logo: 'royal-logo.webp',
        image: 'royal.webp',
        skills: [
            'HTML',
            'CSS',
            'Javascript',
            'Typescript',
            'Angular2',
            'Redux',
        ],
        company: 'Club Assist',
        years: [2016, 2017],
        prevLink: '/project/FitmentPortal',
        nextLink: '/project/Barbie',
    },
    Barbie: {
        title: 'Barbie',
        shortDescription: 'Website',
        description:
            'Contributed to the development of the new Barbie.com website in 2013, aimed at providing a modern and engaging online experience for Barbie fans worldwide. The project involved creating a visually appealing design, implementing interactive features, and optimizing the site for performance and usability across different devices.',
        logo: 'fuel-logo.webp',
        image: 'barbie.webp',
        skills: [
            'Git',
            'Github',
            'HTML',
            'CSS',
            'Javascript',
            'Jquery',
            'Foundation',
        ],
        company: 'Fuel youth',
        years: [2013, 2016],
        prevLink: '/project/Online Check-in',
        nextLink: '/project/Warner Bros Kids',
    },
    'Warner Bros Kids': {
        title: 'Warner Bros Kids',
        shortDescription: 'Website',
        description:
            "Contributed to the development for the launch of the new WBKids.com website. The project aimed to create an immersive and entertaining online experience for kids featuring content from Warner Bros. franchises. Responsibilities included frontend development, implementing interactive features, and ensuring the website's compatibility across different devices.",
        logo: 'fuel-logo.webp',
        image: 'WBkids.webp',
        skills: [
            'Git',
            'Github',
            'HTML',
            'CSS',
            'Javascript',
            'Jquery',
            'Boostrap',
        ],
        company: 'Fuel youth',
        years: [2013, 2016],
        prevLink: '/project/Barbie',
        nextLink: '/project/XFire',
    },
    XFire: {
        title: 'XFire',
        shortDescription: 'Website',
        description:
            "Developed a tournament page in the Xfire website, a gaming social networking platform that allowed gamers to connect with each other, join gaming communities, and share in-game experiences. The website served as the primary hub for users to access Xfire's features and services.",
        logo: 'fuel-logo.webp',
        skills: ['Git', 'Github', 'HTML', 'CSS', 'Javascript', 'AngularJs'],
        company: 'Fuel youth',
        years: [2013, 2016],
        prevLink: '/project/Warner Bros Kids',
        nextLink: '/project/Customer',
    },
    Customer: {
        title: 'Customer',
        shortDescription: 'App module',
        description:
            'Developed a touch screen module to efficiently collect and manage customer information. The module was designed to be user-friendly and intuitive, allowing users to input and access relevant customer details easily. The project aimed to streamline customer data collection processes and improve customer service.',
        logo: 'jitisoft-logo.webp',
        skills: ['HTML', 'CSS', 'Javascript', 'SenchaTouch'],
        company: 'Jitisoft',
        years: [2012, 2013],
        prevLink: '/project/XFire',
        nextLink: '',
    },
};
