import { skillDataType } from "@/definitions/projectDataType";

export const  skillData:Record<string, skillDataType>={
    ["Git"]:{
        name:"Git",
        logoUrl:"git.svg"
    },
    ["Github"]:{
        name:"Github",
        logoUrl:"github.svg"
    },
    ["HTML"]:{
        name:"HTML",
        logoUrl:"html.svg"
    },
    ["CSS"]:{
        name:"CSS",
        logoUrl:"css.svg"
    },
    ["Javascript"]:{
        name:"Javascript",
        logoUrl:"javascript.svg"
    },
    ["Typescript"]:{
        name:"Typescript",
        logoUrl:"typescript.svg"
    },
    ["React"]:{
        name:"React",
        logoUrl:"react.svg"
    },
    ["NodeJs"]:{
        name:"NodeJs",
        logoUrl:"nodejs.svg"
    },
    [".NET"]:{
        name:".NET",
        logoUrl:"net.svg"
    },
    ["GraphQl"]:{
        name:".GraphQl",
        logoUrl:"graphql.svg"
    },
    ["Redux"]:{
        name:"Redux",
        logoUrl:"redux.svg"
    },
    ["Ionic"]:{
        name:"Ionic",
        logoUrl:"ionic.svg"
    },
    ["AngularJs"]:{
        name:"AngularJs",
        logoUrl:"angularjs.svg"
    },
    ["Angular2"]:{
        name:"Angular2",
        logoUrl:"angularjs.svg"
    },
    ["Jquery"]:{
        name:"Jquery",
        logoUrl:"jquery.svg"
    },
    ["Foundation"]:{
        name:"Foundation",
        logoUrl:"foundation.svg"
    },
    ["Boostrap"]:{
        name:"Boostrap",
        logoUrl:"bootsrap.svg"
    },
    ["SenchaTouch"]:{
        name:"SenchaTouch",
        logoUrl:"sencha.svg"
    },
    ["Sharepoint"]:{
        name:"Sharepoint",
        logoUrl:"sencha.svg"
    },


}
